load("@rules_python//python:defs.bzl", "py_library")
load("@my_deps//:requirements.bzl", "requirement")


py_library(
  name = "code_generator",
  srcs = ["python_code_generator.py", "code_generator.py"],
  visibility = ["//visibility:public"],
)