load("@rules_python//python:defs.bzl", "py_library")
load("@my_deps//:requirements.bzl", "requirement")


py_library(
  name = "build_file_generator",
  srcs = ["python_build_file_generator.py", "build_file_generator.py"],
  visibility = ["//visibility:public"],
)